

services:
  flarum:
    image: mondedie/flarum:latest
    container_name: flarum
    env_file:
      - /flarum.env
    volumes:
      - /mnt/docker/flarum/assets:/flarum/app/public/assets
      - /mnt/docker/flarum/extensions:/flarum/app/extensions
      - /mnt/docker/flarum/storage/logs:/flarum/app/storage/logs
      - /mnt/docker/flarum/nginx:/etc/nginx/flarum
    ports:
      - 5000:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=admin
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8081:80 # Mapea el puerto 8081 de tu máquina al puerto 80 del contenedor
    environment:
      - PMA_HOST=mariadb # El nombre del servicio de MariaDB
    depends_on:
      - mariadb